### ISSUE TITLE
Support for crystal 1.x

### ISSUE THREAD

**Issue by waghanza** [phoffer/inflector.cr#2]
Hi @phoffer,

Could you create a new release ?  a `0.2.0` perhaps

Any shards using this one could not be built on `crystal` `1.x` (unless using **master**)

Regards,

**Comment by phoffer** [comment]
Hi @waghanza, I tagged a release and pushed it.

Please let me know if that works for you. Thanks!

**Comment by waghanza** [comment]
Thanks @phoffer. You're library is used as expected in `orion`
https://github.com/the-benchmarker/web-frameworks/blob/crystal/v1/crystal/orion/shard.yml
